# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "scalable-stable" branch
  push:
    branches: [ "scalable-stable", "scalable-edge" ]
  pull_request:
    branches: [ "scalable-stable", "scalable-edge" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install Charmcraft
        run: sudo snap install charmcraft --classic

      - name: Pack with Charmcraft
        run: charmcraft pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: landscape-scalable
          path: ./*.zip
